Repository paketo-buildpacks/libjvm, pull requests merged in 2021-08, with the labels that each got.

#87 Fixes Github issue #84
  count/count_classes.go
  count/count_classes_test.go
Labels: type:bug, semver:patch

#83 Make memory calculator work with cgroups v2
  cmd/helper/main.go
  helper/memory_calculator.go
  helper/memory_calculator_test.go
Labels: semver:minor, type:enhancement

#90 GH issue 81
  build.go
  build_test.go
Labels: semver:minor, type:enhancement

#93 Bump Libpak 1.52.2
  go.mod
  go.sum
  jre.go
Labels: type:dependency-upgrade, semver:patch
