Repository paketo-buildpacks/libjvm, pull requests merged in 2022-05, with the labels that each got.

#166 Adds support for counting agent jar classes in memory calculator
  .gitignore
  count/count_classes.go
  helper/memory_calculator.go
  helper/memory_calculator_test.go
Labels: semver:patch, type:enhancement

#167 Mem calc filetype
  count/count_classes.go
  count/count_classes_test.go
Labels: type:bug, semver:patch

#171 Support SDKMAN RC files
  build.go
  init_test.go
  jvm_version.go
  jvm_version_test.go
  sdkman.go
  sdkman_test.go
Labels: semver:minor, type:enhancement

#173 Added counting of nested Jars 1 level down
  count/count_classes.go
  count/count_classes_test.go
  count/testdata/nested/stub-dependency.jar
Labels: semver:minor, type:enhancement
