Repository paketo-buildpacks/libjvm, pull requests merged in 2022-03, with the labels that each got.

#154 Fix log message prints "METADATA.MF" instead of "MANIFEST.MF"
  jvm_version.go
Labels: type:bug, semver:patch

#153 Add NewJarManifest function to retrieve MANIFEST from a JAR file
  init_test.go
  manifest.go
  manifest_test.go
Labels: semver:minor, type:enhancement

#157 Added link to Memory Calculator detail in docs
  helper/memory_calculator.go
Labels: semver:patch, type:enhancement
