Repository paketo-buildpacks/libjvm, pull requests merged in 2022-08, with the labels that each got.

#192 Fixes to ensure go updates work
  certificate_loader.go
  certificate_loader_test.go
  go.mod
  go.sum
  helper/openssl_certificate_loader_test.go
  jdk_test.go
  jre_test.go
  nik_test.go
Labels: type:dependency-upgrade, semver:minor

#196 Update Pipeline to 1.25.2
  .github/pipeline-version
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-pipeline.yml
Labels: type:task, semver:patch

#200 Sets relevant paths as group-writable to support Jammy stack
  jdk.go
  jlink.go
  jre.go
  nik.go
Labels: semver:patch, type:enhancement
